### ISSUE TITLE
Update merit order documentation to reflect flexibility and battery changes

### ISSUE THREAD

**Issue by antw** [quintel/documentation#101]
As the flexibility project concludes, [the merit order documentation](https://docs.energytransitionmodel.com/main/merit-order/) must be updated to reflect the changes made by this project:

- [x] Flexibility options can consume from dispatchables when willing to pay the market price.
- [x] Flexibility options can set the market price.
- [x] Import and export are always on, function largely as dispatchable and flexible consumer respectively.
- [x] Description of forecasting behaviour.

Changes can be made on the price-sensitive-flex branch. Please add to the list anything I've forgotten.

**Comment by mabijkerk** [comment]
@antw I have written an updated description for `Electricity conversion` and `Electricity storage`. In both I have made references to the merit order. Could you check these descriptions? Perhaps you would like to restructure the `Merit order` page and move some of these description there, to have a more centralised documentation.

The points in the comment above are still open. It would be much appreciated if you could write a description of the forecasting behaviour on the `Electricity storage` page.

**Comment by mabijkerk** [comment]
After these changes have been made, I will check the ETModel locales to see if any references need to be updated.

**Comment by antw** [comment]
I made some minor edits, but I think the docs are good to go. The points I mentioned in the original post are all covered already to some extent with the description of the pricing behaviour. I'll create a PR.
