### ISSUE TITLE
Add documentation about GQL 

### ISSUE THREAD

**Issue by redekok** [quintel/documentation#159]
The old documentation included a [section](https://github.com/quintel/documentation/blob/6c07714bf3cbe86e66331314f4076408ed4f7478/general/GQL.md) about GQL methods and syntax. This should be included in the current documentation (for contributors) as well.

**Comment by mabijkerk** [comment]
See https://github.com/quintel/etengine/tree/master/app/models/gql for all the GQL.

**Comment by mabijkerk** [comment]
Closed with https://github.com/quintel/documentation/pull/178
