### ISSUE TITLE
Improve documentation for installing the ETM on fresh installed laptops

### ISSUE THREAD

**Issue by wouterterlouw** [quintel/documentation#21]
Since my Mac got a fresh install when I left QI after my internship, I had the privilege to go through the installation of etsource, atlas, etengine and etmodel once again. During this installation I came across the following issues which might require additional tips and tricks in the documentation. Some of them may be included in https://github.com/quintel/internal/blob/master/developer/laptop_setup.md, but I think it will be nice if the installation manuals for ETengine and ETmodel are self sufficient.

##### Issues

1. First of all I had some issues with running "bundle install" in various repositories. Part of the problem was because I was 'using'  the local ruby version (see issue https://github.com/quintel/etengine/issues/698). Installing and well configuring rbenv solved the issue. 

2. Furthermore, I was not able to install the mysql2 gem. Running `brew install mysql` was enough to get further.

3. After running bundle install, I tried to create the databases with "bundle exec rake db:create", but got the following error: `Couldn't create database for {"adapter"=>"mysql2", "database"=>"etengine_dev", "host"=>"127.0.0.1", "username"=>"root", "password"=>nil, "encoding"=>"utf8", "timeout"=>5000}, {:charset=>"utf8", :collation=>"utf8_unicode_ci"}`. To solve this I needed to fire up the mysql server with `mysql.server start`:

  ```
➜  etengine git:(master) bundle exec rake db:create
Couldn't create database for {"adapter"=>"mysql2", "database"=>"etengine_dev", "host"=>"127.0.0.1", "username"=>"root", "password"=>nil, "encoding"=>"utf8", "timeout"=>5000}, {:charset=>"utf8", :collation=>"utf8_unicode_ci"}
(If you set the charset manually, make sure you have a matching collation)
Couldn't create database for {"adapter"=>"mysql2", "database"=>"etengine_test", "host"=>"127.0.0.1", "username"=>"root", "password"=>nil, "encoding"=>"utf8", "timeout"=>5000, "pool"=>5}, {:charset=>"utf8", :collation=>"utf8_unicode_ci"}
(If you set the charset manually, make sure you have a matching collation)
➜  etengine git:(master) mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
➜  etengine git:(master) brew install mysql
Warning: mysql-5.6.17_1 already installed
➜  etengine git:(master) mysql.server start
Starting MySQL
. SUCCESS!
  ```

4. When I tried to run "bundle exec cap staging db2local", I got the following error:

  ```
➜  etengine git:(master) bundle exec cap staging db2local
  * 2014-05-20 14:05:04 executing `staging'
  * executing "cat /u/apps/etengine/shared/config/database.yml"
    servers: ["beta.et-engine.com"]
connection failed for: beta.et-engine.com (Net::SSH::AuthenticationFailed: Authentication failed for user ubuntu@beta.et-engine.com)
  ```

  Clearly I was in need of a correct ssh key. To solve this I needed to get a ssh key from QI, add that key to the ~/.ssh/ directory and create a ~/.ssh/config file to redirect to the correct ssh key:

  ```
Host beta.et-engine.com
  IdentityFile ~/.ssh/key_name 
Host beta.et-model.com
  IdentityFile ~/.ssh/key_name
Host github.com
  IdentityFile ~/.ssh/id_rsa
  ```

5. Finally, I also needed to install gnupg ("brew install gnupg") to run the encryption of the energy balance.

Considering the above, it would be nice...
- [ ] if we can add how to run rbenv and mysql correctly, how to fire up the mysql server, ...
- [ ] if we can explain what is required to get the data from beta.et-engine and how you can obtain a ssh key
- [ ] if we have more information about the encryption stuff

##### General recommendations

Beside the specific issues I have some general recommendations:
- [ ] The ETsource reposidory does not have an installation part in the readme. It would be nice if we could add this, even if you only have to run `bundle install`.
- [ ] The ETengine does have two installation parts, a short one in the beginning and a somewhat longer one. I think that if we combine those, the instructions will be clearer. Perhaps we can also include something about running the application with pow.
- [ ] The ETmodel installation guide is fine, but can be extended regarding the optins in the config.yml file. Perhaps we can also include something about running the application with pow.

**Comment by jorisberkhout** [comment]
Reassigning to @twilkinson573 as he has most recently installed the ETM on a laptop.

**Comment by twilkinson573** [comment]
This will be closed by https://github.com/quintel/internal/pull/1

**Comment by jorisberkhout** [comment]
Closed by https://github.com/quintel/internal/pull/1
