### ISSUE TITLE
CO2-calculation principle is missing

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/documentation#35]
See https://github.com/quintel/documentation/blob/master/general/co2_calculations.md:

## Dashboard CO2 calculation

In the dashboard CO2 calculation we calculate the CO2 emission associated with all final energy consumption in the area. Therefore these numbers do not include CO2 emission from the conversion sector within the area that is associated with exported energy (currently only electricity). CO2 that is emited outside the area to produce electricity that is final energy consumption in the area is included. This calculation principle is commonly called **insert name of principle here**

**Comment by ChaelKruip** [comment]
I think the person writing this was bluffing 😄 
Perhaps we should remove the line altogether @AlexanderWirtz?
