### ISSUE TITLE
Update documentation for local datasets with no-go's for editing *.ad files

### ISSUE THREAD

**Issue by grdw** [quintel/documentation#37]
- Don't edit the `interconnector_capacity` because it doesn't reflect in the scaled graph.yml
- Don't edit the scaler `has_industry`, `has_energy` attributes for that doesn't matter, use the default flags instead.
- Don't edit the `base_value` because it doesn't reflect in the scaled graph.yml

**Comment by grdw** [comment]
Solved with https://github.com/quintel/documentation/commit/0d3a46dbb06e466e9a71b1a971dc20e564b2ce0c#diff-69f501521529f659a34f7a908ccddde6R165

**Comment by ploh** [comment]
@grdw I was not aware of your [documentation](https://github.com/quintel/documentation/blob/master/modules/local-datasets/README.markdown) at all. I just updated the [stage 0 document](https://github.com/quintel/internal/blob/master/planning/projects/local-datasets/stage0.md). Please consolidate the two - the `documentation` repo is of course the better place for this :smile: - and refer to the consolidated version from all other places.

Especially, your document does not mention the two unscaled attributes that are mentioned in stage0.
