### ISSUE TITLE
Describe our data-sources and how we use them

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/documentation#46]
We don't have a concise overview of our data sources and people are asking for it...

**Comment by michieldenhaan** [comment]
Not sure what you mean exactly, an overview of our data sources for local datasets?

**Comment by ChaelKruip** [comment]
> Not sure what you mean exactly, an overview of our data sources for local datasets?

Yes! I was a bit vague indeed. I think people need to be able to learn:
* that we use CBS/Klimaatmonitor and how these are used together
* where and how we use extra data and assumptions and their sources
* how our model 'reproduces' statistical results and where deviations occur and why

**Comment by michieldenhaan** [comment]
We do have a doc with a general overview of our data sources (ETLocal folder on Dropbox, see screenshot below). An in-depth description of our corrections can be found here: https://refman.energytransitionmodel.com/publications/2098 (we refer to this document in ETLocal commits)


![20190815_bronnen_aannames_datasets_Quintel (page 1 of 5) 2019-08-15 12-02-59](https://user-images.githubusercontent.com/32056448/63088240-a3eeb900-bf54-11e9-87de-4166ec0486e6.png)

**Comment by ChaelKruip** [comment]
> We do have a doc with a general overview of our data sources (ETLocal folder on Dropbox, see screenshot below)

Nice! perhaps we should put this in Markdown/Wiki and add it to our online documentation?

**Comment by michieldenhaan** [comment]
Closed: https://docs.energytransitionmodel.com/main/data-sources-local
