### ISSUE TITLE
Can we remove the "Currently under validation" warning from the Network documentation?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/documentation#47]
The documentation regarding [network calculations](https://github.com/quintel/documentation/blob/master/general/network.md) still has (Currently under validation) in its header. Can I remove this?

![image](https://user-images.githubusercontent.com/19907658/65493500-433b9000-deb3-11e9-8757-230419210183.png)

Asking @jorisberkhout @MartLubben and @ChaelKruip because you attributed to this page

**Comment by MartLubben** [comment]
According to me you can remove it.

**Comment by DorinevanderVlies** [comment]
Done and closing this issue.
Please re-open if you disagree
