### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/documentation#55]
Link to:

https://github.com/quintel/documentation/blob/master/general/insulation.md

As mentioned here:

https://pro.energytransitionmodel.com/scenario/demand/buildings/insulation

Should likely be something like:

https://github.com/quintel/documentation/blob/master/docs/main/insulation.md

Apparently, there are more instances like this.

@noracato is it possible to automatically look for broken links or is this manual work?

**Comment by michieldenhaan** [comment]
This has been fixed on Beta! I did a global search on ETModel and cannot find any other old links.
We can simply link to `https://docs.energytransitionmodel.com/main/<FILE>` btw
